version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder # Stop at builder stage for development
    command: yarn start
    ports:
      - "8080:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - OPENMRS_BACKEND_URL=http://openmrs-backend:8080/openmrs
      - OPENMRS_PUBLIC_PATH=/openmrs/spa
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - openmrs-network

  openmrs-backend:
    image: openmrs/openmrs-reference-application-3-backend:qa
    ports:
      - "8087:8080"
    environment:
      - DB_HOST=mysql
      - DB_NAME=openmrs
      - DB_USERNAME=openmrs
      - DB_PASSWORD=openmrs
    depends_on:
      - mysql
    networks:
      - openmrs-network

  mysql:
    image: mariadb:11.6.1-ubi9-rc
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=openmrs
      - MYSQL_USER=openmrs
      - MYSQL_PASSWORD=openmrs
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - openmrs-network

volumes:
  mysql-data:

networks:
  openmrs-network:
    driver: bridge